try
{
   // 保护代码
}catch(...)
{
  // 能处理任何异常的代码
}